# Generated by Django 2.1.2 on 2018-10-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='placaMoto',
            field=models.CharField(blank=True, default='', max_length=17, null=True),
        ),
    ]
